name: destroy kilitary.ru
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ssh-pipeline
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          host: kilitary.ru
          port: 22222
          user: deployer
          key: ${{ secrets.PKEY }}
          pass: d3pl0y3r 
          script: |
            cd /home/kilitary/kilitary
            git reset --hard
            git pull
            cp -f public/index.php public/index.php.old
            cp -f public/index.php.off public/index.php
