name: deploy kilitary.ru
#on: [push]
on:
  workflow_dispatch:
jobs:
  deploy:
    name: deploy kilitary
    runs-on: ubuntu-20.04
    steps:
      - name: SSH Execute Commands
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: deployer@kilitary.ru:23
          command: ls -laF
          privateKey: ${{ secrets.PKEY }}
          debug: true
