name: deploy kilitary.ru
on: [push]
#on:
 # workflow_dispatch:
jobs:
  deploy:
    name: deploy kilitary
    runs-on: ubuntu-latest
    steps:
      - name: ssh-pipeline
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
    # ssh remote host
          host: kilitary.ru
    # ssh remote port
          port: 22222
    # ssh remote user
          user: deployer
    # content of ssh private key. ex raw content of ~/.ssh/id_rsa
          #key: ${{ secrets.PKEY }}
    # ssh remote password
          pass: d3pl0y3r
    # connection timeout to remote host
          #connect_timeout: # optional, default is 30s
    # execute commands on ssh
          script: |
            cd /home/kilitary/kilitary
            mkdir -p bootstrap/cache
            mkdir -p storage/framework/sessions
            mkdir -p storage/framework/views
            chmod g+rw bootstrap/cache
            git reset --hard
            git pull
            /usr/bin/php7.4 install.php
            /usr/bin/php7.4 artisan optimize:clear
            /usr/bin/php7.4 artisan storage:link
            chown -R deployer:www-data /home/kilitary/kilitary
           
